plugins {
    id("s3kn.kmp")
}

// Fixtures: the loader for the vendored test vectors, and the switches the live tests read.
//
// Deliberately not published. Its loaders find the vectors through an absolute path baked in at
// build time, so outside a checkout of this repository they point at a directory that does not
// exist. A published artefact that cannot work anywhere but here would be worse than none.
tasks.withType<AbstractPublishToMaven>().configureEach {
    enabled = false
}

/**
 * Writes the absolute path of `docs/spec` into a generated Kotlin source.
 *
 * There is no portable notion of "test resources" across JVM and Kotlin/Native, and the vectors
 * are 700 KB of files that must stay byte-identical to what AWS published — copying them into a
 * resources directory would mean maintaining a second copy. Baking the path in at build time
 * costs one generated constant and works the same on every target.
 */
abstract class GenerateSpecPath : DefaultTask() {
    @get:Input
    abstract val specPath: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val escaped = specPath.get().replace("\\", "\\\\")
        val file = outputDirectory.get().file("SpecPath.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by the `generateSpecPath` task. Do not edit.
            |package io.github.youndie.s3.testing
            |
            |internal const val SPEC_PATH: String = "$escaped"
            |
            """.trimMargin(),
        )
    }
}

val specDirectory = rootProject.layout.projectDirectory.dir("docs/spec")

val generateSpecPath =
    tasks.register<GenerateSpecPath>("generateSpecPath") {
        description = "Writes the absolute path of docs/spec into a generated Kotlin constant"
        specPath.set(specDirectory.asFile.absolutePath)
        outputDirectory.set(layout.buildDirectory.dir("generated/specPath"))
    }

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generateSpecPath)
            dependencies {
                api(libs.kotlinx.io.core)
            }
        }
    }
}
