plugins {
    kotlin("multiplatform")
    id("io.github.youndie.sborka.kmp")
    id("io.github.youndie.sborka.lint")
    id("io.github.youndie.sborka.publish")
}

// Fixtures: the loader for the vendored test vectors, and the switches the live tests read.
//
// Deliberately not published. Its loaders find the vectors through an absolute path baked in at
// build time, so outside a checkout of this repository they point at a directory that does not
// exist. A published artefact that cannot work anywhere but here would be worse than none.
//
// `sborka.publish` is still applied, and on purpose: the guard below is what says "not published",
// and a guard over tasks that do not exist guards nothing. Applied and disabled, the day someone
// removes these four lines the module starts publishing and the removal is the visible cause.
tasks.withType<AbstractPublishToMaven>().configureEach {
    enabled = false
}

/**
 * Writes the absolute path of `docs/spec` into a generated Kotlin source.
 *
 * There is no portable notion of "test resources" across JVM and Kotlin/Native, and the vectors
 * are 700 KB of files that must stay byte-identical to what AWS published — copying them into a
 * resources directory would mean maintaining a second copy. Baking the path in at build time
 * costs one generated constant and works the same on every target.
 */
abstract class GenerateSpecPath : DefaultTask() {
    @get:Input
    abstract val specPath: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val escaped = specPath.get().replace("\\", "\\\\")
        val file = outputDirectory.get().file("SpecPath.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by the `generateSpecPath` task. Do not edit.
            |package io.github.youndie.s3.testing
            |
            |internal const val SPEC_PATH: String = "$escaped"
            |
            """.trimMargin(),
        )
    }
}

val specDirectory = rootProject.layout.projectDirectory.dir("docs/spec")

val generateSpecPath =
    tasks.register<GenerateSpecPath>("generateSpecPath") {
        description = "Writes the absolute path of docs/spec into a generated Kotlin constant"
        specPath.set(specDirectory.asFile.absolutePath)
        outputDirectory.set(layout.buildDirectory.dir("generated/specPath"))
    }

kotlin {
    // THE TARGETS STAY HERE, and the reasons with them. `sborka.kmp` gives the mechanics — explicit
    // API, the toolchain, warnings as errors, the jvm target compiled to the floor — and declares no
    // target of its own: the set below is a decision this repository argued out, not a portfolio
    // default.
    //
    // Target platform number one; milestones are closed against it. Apple: the engine there is
    // `ktor-client-darwin` — `ktor-client-curl` publishes nothing for iOS at all
    // (docs/research/research-architecture.md, fact 1.11). `watchos` and `tvos` are left out although
    // every dependency publishes them: no test has ever run there, and "it compiles" is a different
    // claim from "it works". `macosX64` is left out for a stronger reason: Kotlin has deprecated the
    // target and nothing here has ever run on it.
    jvm()
    linuxX64()
    macosArm64()
    iosArm64()
    iosSimulatorArm64()
    iosX64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateSpecPath)
            dependencies {
                api(libs.kotlinx.io.core)
            }
        }
    }
}
