plugins {
    kotlin("multiplatform")
    id("io.github.youndie.sborka.kmp")
    id("io.github.youndie.sborka.lint")
}

// The command-line client: one binary that copies objects in and out, and the reason the library
// finally has a consumer that is not its own test suite (docs/features/feature-cli.md).
//
// It is deliberately NOT published to Maven. What this module produces is an executable and an
// image; a klib of it would have no consumer, and `sborka.publish` is therefore not applied at all
// — unlike `:s3-testing`, where the plugin is applied and its tasks disabled because the module
// once looked publishable.

/**
 * Writes the project version into a generated Kotlin source.
 *
 * `s3kn --version` has to answer with something that can be matched against an image tag, and the
 * version lives in `gradle.properties`. Reading it at build time is the only way the binary and the
 * artefact cannot disagree — a constant typed into a source file drifts on the first release
 * nobody remembers to edit.
 */
abstract class GenerateVersion : DefaultTask() {
    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val file = outputDirectory.get().file("Version.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by the `generateVersion` task. Do not edit.
            |package io.github.youndie.s3.cli
            |
            |internal const val CLI_VERSION: String = "${version.get()}"
            |
            """.trimMargin(),
        )
    }
}

val generateVersion =
    tasks.register<GenerateVersion>("generateVersion") {
        description = "Writes the project version into a generated Kotlin constant"
        version.set(project.version.toString())
        outputDirectory.set(layout.buildDirectory.dir("generated/version"))
    }

kotlin {
    // NOT A LIBRARY: nothing here is published and nothing depends on it, so there is no consumer for
    // a spelled-out public API to be spelled out FOR. `sborka.kmp` turns explicit API on because that
    // is right for the four modules that are published; this switches it back off for the ones that
    // are binaries. The rest of what the convention brings — the toolchain, warnings as errors — is
    // wanted here as much as anywhere.
    explicitApi = null

    // TWO TARGETS, AND THE SECOND ONE IS NOT SHIPPED. `linuxX64` is what goes into the image and
    // what the milestone closes against. `macosArm64` exists because `linuxX64Test` does not run on
    // a macOS host at all — KGP disables the task — so without it the local loop would have no way
    // to run a single test of this module. The binary it produces is a working `s3kn` on a laptop,
    // which is a side effect and not a promise: nothing publishes it.
    linuxX64 {
        binaries.executable {
            entryPoint = "io.github.youndie.s3.cli.main"
            // The image copies this file by name. Spelled here so that renaming the module does not
            // silently rename the artefact the Dockerfile looks for.
            baseName = "s3kn"
            linkerOpts.add("-Wl,--as-needed")
        }
    }
    macosArm64 {
        binaries.executable {
            entryPoint = "io.github.youndie.s3.cli.main"
            baseName = "s3kn"
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateVersion)
            dependencies {
                implementation(projects.s3Client)
            }
        }
        nativeMain.dependencies {
            // Files. The only file API that exists on every native target this repository builds.
            implementation(libs.kotlinx.io.core)
        }
        // The engine, per target, for the same reason the library never picks one: on linuxX64 curl
        // is the only thing that speaks HTTPS (research, fact 1.1) and on Apple it is Darwin.
        linuxX64Main.dependencies {
            implementation(libs.ktor.client.curl)
        }
        macosArm64Main.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest.dependencies {
            implementation(libs.kotlinx.coroutines.test)
        }
        nativeTest.dependencies {
            implementation(projects.s3Testing)
        }
    }
}
